import { toDevanagari, toOlChiki } from "./translit";

export type LangCode = "sat" | "hoc" | "unr";

export type LangMeta = {
  code: LangCode;
  name: string;
  nativeName: string;
  script: string;
  speakers: string;
  ttsLocale: string;
};

export const LANGUAGES: LangMeta[] = [
  {
    code: "sat",
    name: "Santhali",
    nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",
    script: "Ol Chiki",
    speakers: "~7.4 million",
    ttsLocale: "hi-IN",
  },
  {
    code: "hoc",
    name: "Ho",
    nativeName: "𑢹𑣉𑣉",
    script: "Warang Citi",
    speakers: "~1.4 million",
    ttsLocale: "hi-IN",
  },
  {
    code: "unr",
    name: "Mundari",
    nativeName: "मुंडारी",
    script: "Devanagari",
    speakers: "~1.1 million",
    ttsLocale: "hi-IN",
  },
];

export const getLang = (code: LangCode): LangMeta =>
  LANGUAGES.find((l) => l.code === code) ?? (LANGUAGES[0] as LangMeta);

/** roman transliteration + native script form */
export type Gloss = { roman: string; native: string };
export type Entry = Record<LangCode, Gloss>;

const e = (
  sat: [string, string],
  hoc: [string, string],
  unr: [string, string],
): Entry => ({
  sat: { roman: sat[0], native: sat[1] },
  hoc: { roman: hoc[0], native: hoc[1] },
  unr: { roman: unr[0], native: unr[1] },
});

/**
 * Prototype FLN lexicon. Hindi headword -> tribal-language glosses.
 * Curated from PALASH MTB-MLE primary-grade word lists. Community
 * verification by native speakers is required before classroom rollout.
 */
export const LEXICON: Record<string, Entry> = {
  // greetings & classroom talk
  नमस्ते: e(["johar", "ᱡᱚᱦᱟᱨ"], ["johar", "𑢠𑣉𑣁𑣜"], ["johar", "जोहार"]),
  नमस्कार: e(["johar", "ᱡᱚᱦᱟᱨ"], ["johar", "𑢠𑣉𑣁𑣜"], ["johar", "जोहार"]),
  बच्चों: e(["gidrako", "ᱜᱤᱫᱽᱨᱟᱹᱠᱚ"], ["hoponko", "𑣙𑣉𑣟𑣉𑣃"], ["hongoko", "होनको"]),
  बच्चा: e(["gidra", "ᱜᱤᱫᱽᱨᱟᱹ"], ["hopon", "𑣙𑣉𑣟𑣉"], ["hon", "होन"]),
  बैठो: e(["durup me", "ᱫᱩᱨᱩᱯ ᱢᱮ"], ["dub me", "𑣞𑣂𑣜 𑣢𑣕"], ["dub me", "दुब मे"]),
  उठो: e(["tingun me", "ᱛᱤᱝᱜᱩᱱ ᱢᱮ"], ["tingun me", "𑣔𑣂𑣂 𑣢𑣕"], ["tingu me", "तिंगु मे"]),
  सुनो: e(["anjom me", "ᱟᱸᱡᱚᱢ ᱢᱮ"], ["ayum me", "𑣁𑣜𑣂𑣢 𑣢𑣕"], ["ayum me", "आयुम मे"]),
  देखो: e(["nel me", "ᱧᱮᱞ ᱢᱮ"], ["nel me", "𑣙𑣕𑣗 𑣢𑣕"], ["nel me", "नेल मे"]),
  बोलो: e(["ror me", "ᱨᱚᱲ ᱢᱮ"], ["kaji me", "𑣄𑣁𑣄𑣂 𑣢𑣕"], ["kaji me", "काजी मे"]),
  पढ़ो: e(["padhao me", "ᱯᱟᱲᱦᱟᱣ ᱢᱮ"], ["parhao me", "𑣟𑣁𑣜𑣁𑣉 𑣢𑣕"], ["parhao me", "पड़हाव मे"]),
  लिखो: e(["ol me", "ᱚᱞ ᱢᱮ"], ["ol me", "𑣉𑣗 𑣢𑣕"], ["ol me", "ओल मे"]),
  अच्छा: e(["bes", "ᱵᱮᱸᱥ"], ["bugin", "𑣢𑣂𑣍𑣂"], ["bugin", "बुगिन"]),
  शाबाश: e(["bes kana", "ᱵᱮᱥ ᱠᱟᱱᱟ"], ["bugin tana", "𑣢𑣂𑣍𑣂 𑣔𑣁𑣙"], ["bugin tana", "बुगिन ताना"]),
  हाँ: e(["hõ", "ᱦᱩᱭ"], ["hõ", "𑣁𑣉"], ["hõ", "हँ"]),
  नहीं: e(["bang", "ᱵᱟᱝ"], ["ka", "𑣄𑣁"], ["ka", "का"]),
  धन्यवाद: e(["sarhao", "ᱥᱟᱨᱦᱟᱣ"], ["sarhao", "𑣜𑣁𑣜𑣁𑣉"], ["sarhao", "सरहाव"]),

  // people
  माँ: e(["ayo", "ᱟᱭᱳ"], ["enga", "𑣕𑣍𑣁"], ["enga", "एंगा"]),
  पिता: e(["baba", "ᱵᱟᱵᱟ"], ["apu", "𑣁𑣟𑣂"], ["apu", "आपू"]),
  गुरुजी: e(["guruji", "ᱜᱩᱨᱩᱡᱤ"], ["guruji", "𑣍𑣂𑣜𑣂𑣄𑣂"], ["guruji", "गुरुजी"]),
  दोस्त: e(["gate", "ᱜᱟᱛᱮ"], ["gati", "𑣍𑣁𑣔𑣂"], ["gati", "गाती"]),
  लड़का: e(["kora", "ᱠᱚᱲᱟ"], ["koa", "𑣄𑣉𑣁"], ["koa", "कोआ"]),
  लड़की: e(["kuri", "ᱠᱩᱲᱤ"], ["kui", "𑣄𑣂𑣂"], ["kui", "कुई"]),

  // school objects
  स्कूल: e(["askul", "ᱟᱥᱠᱩᱞ"], ["skul", "𑣜𑣄𑣂𑣗"], ["skul", "स्कूल"]),
  किताब: e(["puthi", "ᱯᱩᱛᱷᱤ"], ["puthi", "𑣟𑣂𑣜𑣂"], ["puthi", "पुथी"]),
  कलम: e(["kalam", "ᱠᱚᱞᱚᱢ"], ["kalam", "𑣄𑣁𑣗𑣢"], ["kalam", "कलम"]),
  पानी: e(["dak", "ᱫᱟᱜᱽ"], ["daa", "𑣞𑣁𑣁"], ["daa", "दाआ"]),
  घर: e(["orak", "ᱚᱲᱟᱜᱽ"], ["oa", "𑣉𑣁"], ["oa", "ओआ"]),
  खाना: e(["jom", "ᱡᱚᱢ"], ["jom", "𑣄𑣉𑣢"], ["jom", "जोम"]),
  गाँव: e(["atu", "ᱟᱛᱩ"], ["hatu", "𑣁𑣔𑣂"], ["hatu", "हातू"]),

  // nature
  सूरज: e(["singi", "ᱥᱤᱸᱜᱤ"], ["singi", "𑣜𑣂𑣍𑣂"], ["singi", "सिंगी"]),
  चाँद: e(["chando", "ᱪᱟᱸᱫᱚ"], ["chandu", "𑣋𑣁𑣞𑣂"], ["chandu", "चांदू"]),
  पेड़: e(["dare", "ᱫᱟᱨᱮ"], ["daru", "𑣞𑣁𑣜𑣂"], ["daru", "दारू"]),
  फूल: e(["baha", "ᱵᱟᱦᱟ"], ["baa", "𑣢𑣁𑣁"], ["baa", "बाआ"]),
  नदी: e(["gada", "ᱜᱟᱰᱟ"], ["gada", "𑣍𑣁𑣞𑣁"], ["gada", "गाड़ा"]),
  पहाड़: e(["buru", "ᱵᱩᱨᱩ"], ["buru", "𑣢𑣂𑣜𑣂"], ["buru", "बुरू"]),
  आग: e(["sengel", "ᱥᱮᱸᱜᱮᱞ"], ["sengel", "𑣜𑣕𑣍𑣕𑣗"], ["sengel", "सेंगेल"]),
  बारिश: e(["dak", "ᱫᱟᱜᱽ ᱜᱟᱫᱟ"], ["gama", "𑣍𑣁𑣢𑣁"], ["gama", "गामा"]),

  // animals
  गाय: e(["gai", "ᱜᱟᱭ"], ["uri", "𑣂𑣜𑣂"], ["uri", "उरी"]),
  कुत्ता: e(["seta", "ᱥᱮᱛᱟ"], ["seta", "𑣜𑣕𑣔𑣁"], ["seta", "सेता"]),
  बकरी: e(["merom", "ᱢᱮᱨᱚᱢ"], ["merom", "𑣢𑣕𑣜𑣉𑣢"], ["merom", "मेरोम"]),
  चिड़िया: e(["chene", "ᱪᱮᱬᱮ"], ["chene", "𑣋𑣕𑣙𑣕"], ["chene", "चेने"]),
  मछली: e(["hako", "ᱦᱟᱠᱩ"], ["hai", "𑣁𑣅"], ["hai", "हाई"]),
  बिल्ली: e(["pusi", "ᱯᱩᱥᱤ"], ["pusi", "𑣟𑣂𑣜𑣂"], ["pusi", "पुसी"]),
  म्याऊं: e(["meao", "ᱢᱮᱭᱟᱣ"], ["miaw", "𑣢𑣂𑣁𑣓"], ["miaw", "मियाव"]),
  म्याऊँ: e(["meao", "ᱢᱮᱭᱟᱣ"], ["miaw", "𑣢𑣂𑣁𑣓"], ["miaw", "मियाव"]),
  "म्याऊं म्याऊं": e(["meao meao", "ᱢᱮᱭᱟᱣ ᱢᱮᱭᱟᱣ"], ["miaw miaw", "𑣢𑣂𑣁𑣓 𑣢𑣂𑣁𑣓"], ["miaw miaw", "मियाव मियाव"]),
  "म्याऊँ म्याऊँ": e(["meao meao", "ᱢᱮᱭᱟᱣ ᱢᱮᱭᱟᱣ"], ["miaw miaw", "𑣢𑣂𑣁𑣓 𑣢𑣂𑣁𑣓"], ["miaw miaw", "मियाव मियाव"]),

  // body
  आँख: e(["med", "ᱢᱮᱫᱽ"], ["med", "𑣢𑣕𑣞"], ["med", "मेद"]),
  हाथ: e(["ti", "ᱛᱤ"], ["ti", "𑣔𑣂"], ["ti", "ती"]),
  सिर: e(["bohok", "ᱵᱚᱦᱚᱠ"], ["bo", "𑣢𑣉"], ["bo", "बो"]),
  पैर: e(["janga", "ᱡᱟᱝᱜᱟ"], ["kata", "𑣄𑣁𑣔𑣁"], ["kata", "काता"]),

  // numbers
  एक: e(["mit", "ᱢᱤᱫᱽ"], ["miad", "𑣢𑣂𑣁𑣞"], ["miad", "मियाद"]),
  दो: e(["bar", "ᱵᱟᱨ"], ["baria", "𑣢𑣁𑣜𑣂𑣁"], ["baria", "बारिया"]),
  तीन: e(["pe", "ᱯᱮ"], ["apia", "𑣁𑣟𑣂𑣁"], ["apia", "आपिया"]),
  चार: e(["pon", "ᱯᱩᱱ"], ["upunia", "𑣂𑣟𑣂𑣙𑣂𑣁"], ["upunia", "उपुनिया"]),
  पाँच: e(["more", "ᱢᱚᱬᱮ"], ["monea", "𑣢𑣉𑣙𑣕𑣁"], ["monea", "मोनेया"]),
  छह: e(["turui", "ᱛᱩᱨᱩᱭ"], ["turia", "𑣔𑣂𑣜𑣂𑣁"], ["turia", "तुरिया"]),
  सात: e(["eae", "ᱮᱭᱟᱭ"], ["eaea", "𑣕𑣁𑣕𑣁"], ["eya", "एया"]),
  आठ: e(["irel", "ᱤᱨᱟᱹᱞ"], ["iralia", "𑣂𑣜𑣁𑣗𑣂𑣁"], ["iralia", "इरालिया"]),
  नौ: e(["are", "ᱟᱨᱮ"], ["area", "𑣁𑣜𑣕𑣁"], ["area", "आरेया"]),
  दस: e(["gel", "ᱜᱮᱞ"], ["gelea", "𑣍𑣕𑣗𑣕𑣁"], ["gelea", "गेलेया"]),

  // colours
  लाल: e(["arak", "ᱟᱨᱟᱜᱽ"], ["ara", "𑣁𑣜𑣁"], ["ara", "आरा"]),
  काला: e(["hende", "ᱦᱮᱸᱫᱮ"], ["hende", "𑣁𑣕𑣙𑣞𑣕"], ["hende", "हेंदे"]),
  सफेद: e(["pond", "ᱯᱩᱸᱰ"], ["pund", "𑣟𑣂𑣙𑣞"], ["pund", "पुंड"]),
  हरा: e(["hariar", "ᱦᱟᱲᱤᱭᱟᱨ"], ["hariar", "𑣁𑣜𑣂𑣁𑣜"], ["hariar", "हरियार"]),

  // verbs / FLN instruction words
  आओ: e(["hijuk me", "ᱦᱤᱡᱩᱜᱽ ᱢᱮ"], ["hiju me", "𑣁𑣂𑣄𑣂 𑣢𑣕"], ["hiju me", "हिजू मे"]),
  जाओ: e(["chalak me", "ᱪᱟᱞᱟᱜᱽ ᱢᱮ"], ["senoh me", "𑣜𑣕𑣙𑣉 𑣢𑣕"], ["senoh me", "सेनो मे"]),
  खेलो: e(["enec me", "ᱮᱱᱮᱡ ᱢᱮ"], ["ening me", "𑣕𑣙𑣂𑣍 𑣢𑣕"], ["ening me", "एनिंग मे"]),
  गिनो: e(["lekha me", "ᱞᱮᱠᱷᱟ ᱢᱮ"], ["lekha me", "𑣗𑣕𑣄𑣁 𑣢𑣕"], ["lekha me", "लेखा मे"]),
  बताओ: e(["udug me", "ᱩᱫᱩᱜᱽ ᱢᱮ"], ["udub me", "𑣂𑣞𑣂𑣢 𑣢𑣕"], ["udub me", "उदुब मे"]),
  दोहराओ: e(["dohrao me", "ᱫᱩᱦᱲᱟᱣ ᱢᱮ"], ["dohrao me", "𑣞𑣉𑣁𑣜𑣁𑣉 𑣢𑣕"], ["dohrao me", "दोहराव मे"]),
  क्या: e(["chet", "ᱪᱮᱫᱽ"], ["chi", "𑣋𑣂"], ["chi", "ची"]),
  कौन: e(["okoe", "ᱚᱠᱚᱭ"], ["okoe", "𑣉𑣄𑣉𑣅"], ["okoe", "ओकोए"]),
  कितने: e(["tinak", "ᱛᱤᱱᱟᱜᱽ"], ["tin", "𑣔𑣂𑣙"], ["tin", "तिन"]),
  आज: e(["tehen", "ᱛᱮᱦᱮᱸ"], ["tisin", "𑣔𑣂𑣜𑣂𑣙"], ["tisin", "तिसिन"]),
  नाम: e(["nutum", "ᱧᱩᱛᱩᱢ"], ["nutum", "𑣙𑣂𑣔𑣂𑣢"], ["nutum", "नुतुम"]),
  तुम्हारा: e(["amak", "ᱟᱢᱟᱜᱽ"], ["amah", "𑣁𑣢𑣁"], ["amaa", "आमा"]),
  मेरा: e(["ingak", "ᱤᱧᱟᱜᱽ"], ["ingaa", "𑣂𑣜𑣂𑣁"], ["ingaa", "इंआ"]),
  है: e(["menak", "ᱢᱮᱱᱟᱜᱽ"], ["mena", "𑣢𑣕𑣙𑣁"], ["mena", "मेना"]),
  और: e(["ar", "ᱟᱨ"], ["ar", "𑣁𑣜"], ["ar", "आर"]),
};

/** Build an entry from roman forms only; native scripts are transliterated. */
const q = (sat: string, hoc: string, unr: string): Entry => ({
  sat: { roman: sat, native: toOlChiki(sat) },
  hoc: { roman: hoc, native: toDevanagari(hoc) },
  unr: { roman: unr, native: toDevanagari(unr) },
});

/** Expanded everyday + classroom vocabulary (roman-first, auto-transliterated). */
const EXTRA_LEXICON: Record<string, Entry> = {
  प्यार: q("dular", "dulad", "dulad"),
  प्रेम: q("dular", "dulad", "dulad"),
  प्यारा: q("dulariya", "dulariya", "dulariya"),
  से: q("te", "te", "te"),
  साथ: q("saonte", "saote", "saote"),
  बात: q("katha", "kaji", "kaji"),
  करें: q("kami bon", "kami bu", "kami bu"),
  करो: q("kami me", "kami me", "kami me"),
  काम: q("kami", "kami", "kami"),
  हम: q("abo", "abu", "abu"),
  तुम: q("am", "am", "am"),
  आप: q("am", "am", "am"),
  मैं: q("ing", "ain", "ain"),
  वह: q("uni", "uni", "uni"),
  यह: q("noa", "nea", "nea"),
  कहाँ: q("okare", "okare", "okare"),
  कब: q("tinre", "tinre", "tinre"),
  क्यों: q("chekate", "chiate", "chiate"),
  कैसे: q("chetlekate", "chilekate", "chilekate"),
  कितना: q("tinak", "tin", "tin"),
  सब: q("jotoh", "sabenko", "sabenko"),
  कुछ: q("tikin", "kicu", "kicu"),
  बहुत: q("adi", "pura", "pura"),
  थोड़ा: q("katich", "huring", "huring"),
  बड़ा: q("maran", "maran", "maran"),
  छोटा: q("huring", "huring", "huring"),
  नया: q("nawa", "nawa", "nawa"),
  बुरा: q("etkec", "etka", "etka"),
  सही: q("thik", "thik", "thik"),
  गलत: q("bhul", "bhul", "bhul"),
  खुश: q("rasika", "suku", "suku"),
  खुशी: q("rasika", "suku", "suku"),
  मन: q("mon", "mon", "mon"),
  दिल: q("mon", "mon", "mon"),
  भाई: q("boeha", "boeya", "haga"),
  बहन: q("misera", "misi", "misi"),
  समय: q("okto", "okto", "okto"),
  दिन: q("mahan", "mahan", "mahan"),
  रात: q("nida", "nida", "nida"),
  सुबह: q("setak", "setag", "setag"),
  शाम: q("ayub", "ayub", "ayub"),
  कल: q("gapa", "gapa", "gapa"),
  अभी: q("nitok", "nahag", "nahag"),
  चलो: q("chalak bon", "senoh bu", "senoh bu"),
  रुको: q("tahen me", "tainge me", "tainge me"),
  मदद: q("gorho", "gora", "gora"),
  सवाल: q("kuli", "kuli", "kuli"),
  जवाब: q("telaa", "ruar", "ruar"),
  सीखो: q("itun me", "itu me", "itu me"),
  समझो: q("bujhau me", "bujhau me", "bujhau me"),
  याद: q("uyhar", "uyhar", "uyhar"),
  फिर: q("ar", "ar", "ar"),
  धीरे: q("alge", "alge", "alge"),
  जल्दी: q("ludhur", "ludhur", "ludhur"),
  गीत: q("sereng", "durang", "durang"),
  गाना: q("sereng", "durang", "durang"),
  नाच: q("enec", "susun", "susun"),
  कहानी: q("kahani", "kahni", "kahni"),
  खेल: q("enec", "ening", "ening"),
  भूख: q("rengec", "rengech", "rengech"),
  प्यास: q("tetang", "tetang", "tetang"),
  दूध: q("toa", "toa", "toa"),
  चावल: q("chaole", "chauli", "chauli"),
  रोटी: q("roti", "roti", "roti"),
  फल: q("jo", "jo", "jo"),
  सब्जी: q("utu", "utu", "utu"),
  अंडा: q("bili", "bili", "bili"),
  पेट: q("lac", "lai", "lai"),
  कान: q("lutur", "lutur", "lutur"),
  मुँह: q("mocha", "moche", "moche"),
  दाँत: q("data", "data", "data"),
  बाल: q("up", "ub", "ub"),
  सो: q("jape me", "jape me", "jape me"),
  ले: q("idi me", "idi me", "idi me"),
  दे: q("em me", "em me", "em me"),
  लो: q("hatao me", "hatao me", "hatao me"),
  खोलो: q("nij me", "nij me", "nij me"),
  बंद: q("banda", "banda", "banda"),
  साफ: q("sapha", "sapha", "sapha"),
  बैठ: q("durup", "dub", "dub"),
  खड़ा: q("tingun", "tingu", "tingu"),
  कहो: q("ror me", "kaji me", "kaji me"),
  पूछो: q("kuli me", "kuli me", "kuli me"),
  नाम: q("nutum", "nutum", "nutum"),
  बच्चे: q("gidrako", "hoponko", "honko"),
  भी: q("hõ", "ho", "ho"),
  में: q("re", "re", "re"),
  का: q("ren", "ren", "ren"),
  को: q("ke", "ke", "ke"),
  हैं: q("menakkoa", "menaakoa", "menaakoa"),
  था: q("tahenkan", "tainkena", "tainkena"),
  थी: q("tahenkan", "tainkena", "tainkena"),
  थे: q("tahenkan", "tainkena", "tainkena"),
  अब: q("nitok", "nahag", "nahag"),

  // Ergative / agentive & oblique pronouns
  तुमने: q("am", "am", "am"),
  मैंने: q("ing", "ain", "ain"),
  उसने: q("uni", "uni", "uni"),
  हमने: q("abo", "abu", "abu"),
  आपने: q("am", "am", "am"),
  इन्होंने: q("nuku", "neko", "neko"),
  उन्होंने: q("onko", "onko", "onko"),
  किसे: q("okoe", "okoe", "okoe"),
  किसने: q("okoe", "okoe", "okoe"),

  // Possessive & oblique pronouns
  तुम्हारी: q("amak", "amah", "amaa"),
  तुम्हारे: q("amak", "amah", "amaa"),
  मेरी: q("ingak", "ingaa", "ingaa"),
  मेरे: q("ingak", "ingaa", "ingaa"),
  हमारा: q("aboak", "abuah", "abuah"),
  हमारी: q("aboak", "abuah", "abuah"),
  हमारे: q("aboak", "abuah", "abuah"),
  उसका: q("unia", "unia", "unia"),
  उसकी: q("unia", "unia", "unia"),
  उसके: q("unia", "unia", "unia"),
  मुझे: q("ing", "ain", "ain"),
  मुझको: q("ing", "ain", "ain"),
  तुम्हें: q("am", "am", "am"),
  तुझको: q("am", "am", "am"),
  उसे: q("uni", "uni", "uni"),
  उसको: q("uni", "uni", "uni"),
  हमें: q("abo", "abu", "abu"),
  हमको: q("abo", "abu", "abu"),
  आपको: q("am", "am", "am"),

  // Copulas & Auxiliaries
  हूं: e(["kana", "ᱠᱟᱱᱟ"], ["tana", "𑣔𑣁𑣙"], ["tana", "ताना"]),
  हूँ: e(["kana", "ᱠᱟᱱᱟ"], ["tana", "𑣔𑣁𑣙"], ["tana", "ताना"]),
  हो: e(["kanam", "ᱠᱟᱱᱟᱢ"], ["tanam", "𑣔𑣁𑣙𑣁𑣢"], ["tana", "ताना"]),
  है: e(["kana", "ᱠᱟᱱᱟ"], ["tana", "𑣔𑣁𑣙"], ["tana", "ताना"]),
  होगा: q("hoyok", "hoba", "hoba"),
  होगी: q("hoyok", "hoba", "hoba"),
  होंगे: q("hoyoka", "hobawa", "hobawa"),

  // Reduplications & questions
  "क्या क्या": q("chet ko", "chi ko", "chi ko"),
  "क्या-क्या": q("chet ko", "chi ko", "chi ko"),

  // Verb past/present/future forms & stems
  सीखा: q("chedket", "itukeda", "itukeda"),
  सीखे: q("chedket", "itukeda", "itukeda"),
  सीखी: q("chedket", "itukeda", "itukeda"),
  सीखेंगे: q("bo tolaawa", "bu itua", "bu itua"),
  सीखना: q("ched", "itu", "itu"),
  सीख: q("ched", "itu", "itu"),
  पढ़ा: q("parhaoket", "parhaokeda", "parhaokeda"),
  पढ़े: q("parhaoket", "parhaokeda", "parhaokeda"),
  पढ़ी: q("parhaoket", "parhaokeda", "parhaokeda"),
  पढ़ेंगे: q("parhaowa", "parhaowa", "parhaowa"),
  पढ़ना: q("parhao", "parhao", "parhao"),
  पढ़: q("parhao", "parhao", "parhao"),
  लिखा: q("olket", "olkeda", "olkeda"),
  लिखे: q("olket", "olkeda", "olkeda"),
  लिखी: q("olket", "olkeda", "olkeda"),
  लिखेंगे: q("olbon", "olbu", "olbu"),
  लिखना: q("ol", "ol", "ol"),
  लिख: q("ol", "ol", "ol"),
  बोला: q("rorket", "kajikeda", "kajikeda"),
  बोले: q("rorket", "kajikeda", "kajikeda"),
  बोली: q("rorket", "kajikeda", "kajikeda"),
  बोलेंगे: q("rorbon", "kajibu", "kajibu"),
  बोलना: q("ror", "kaji", "kaji"),
  बोल: q("ror", "kaji", "kaji"),
  सुना: q("anjomket", "ayumkeda", "ayumkeda"),
  सुने: q("anjomket", "ayumkeda", "ayumkeda"),
  सुनी: q("anjomket", "ayumkeda", "ayumkeda"),
  सुनेंगे: q("anjombon", "ayumbu", "ayumbu"),
  सुनना: q("anjom", "ayum", "ayum"),
  सुन: q("anjom", "ayum", "ayum"),
  देखा: q("nelket", "nelkeda", "nelkeda"),
  देखे: q("nelket", "nelkeda", "nelkeda"),
  देखी: q("nelket", "nelkeda", "nelkeda"),
  देखेंगे: q("nelbon", "nelbu", "nelbu"),
  देखना: q("nel", "nel", "nel"),
  देख: q("nel", "nel", "nel"),
  खाया: q("jomket", "jomkeda", "jomkeda"),
  खाए: q("jomket", "jomkeda", "jomkeda"),
  खाई: q("jomket", "jomkeda", "jomkeda"),
  खाएंगे: q("jombon", "jombu", "jombu"),
  खा: q("jom", "jom", "jom"),
  पिया: q("nuket", "nukeda", "nukeda"),
  पिए: q("nuket", "nukeda", "nukeda"),
  पी: q("nu", "nu", "nu"),
  पिएंगे: q("nubon", "nubu", "nubu"),
  पीना: q("nu", "nu", "nu"),
  गया: q("senlen", "senkena", "senkena"),
  गए: q("senlen", "senkena", "senkena"),
  गई: q("senlen", "senkena", "senkena"),
  जाएंगे: q("chalakbon", "senohbu", "senohbu"),
  जाना: q("chalak", "senoh", "senoh"),
  जा: q("chalak", "senoh", "senoh"),
  आया: q("heclen", "hijukena", "hijukena"),
  आए: q("heclen", "hijukena", "hijukena"),
  आई: q("heclen", "hijukena", "hijukena"),
  आएंगे: q("hijukbon", "hijubu", "hijubu"),
  आना: q("hijuk", "hiju", "hiju"),
  आ: q("hijuk", "hiju", "hiju"),
  किया: q("kamiket", "kamikeda", "kamikeda"),
  किए: q("kamiket", "kamikeda", "kamikeda"),
  की: q("kamiket", "kamikeda", "kamikeda"),
  करेंगे: q("kamibon", "kamibu", "kamibu"),
  करना: q("kami", "kami", "kami"),
  कर: q("kami", "kami", "kami"),

  // Onomatopoeia & animals
  "भौ भौ": q("bhoo bhoo", "bhoo bhoo", "bhoo bhoo"),
  "भौं भौं": q("bhoo bhoo", "bhoo bhoo", "bhoo bhoo"),
  "चीं चीं": q("chene radam", "chin chin", "chin chin"),

  // Transliterated Hinglish speech words
  हेलो: q("johar", "johar", "johar"),
  हलो: q("johar", "johar", "johar"),
  हेल्लो: q("johar", "johar", "johar"),
  हे: q("johar", "johar", "johar"),
  हाय: q("johar", "johar", "johar"),
  हाउ: q("chetlekate", "chilekate", "chilekate"),
  आर: q("kanam", "tanam", "tana"),
  यू: q("am", "am", "am"),
  आय: q("ing", "ain", "ain"),
  एम: q("kana", "tana", "tana"),
  माय: q("ingak", "ingaa", "ingaa"),
  नेम: q("nutum", "nutum", "nutum"),
  इज: q("kana", "tana", "tana"),
  व्हाट: q("chet", "chi", "chi"),
  व्हाट्स: q("chet kana", "chi tana", "chi tana"),
  योर: q("amak", "amah", "amaa"),
  गुड: q("bes", "bugin", "bugin"),
  मॉर्निंग: q("setak", "setag", "setag"),
  थैंक्यू: q("sarhao", "sarhao", "sarhao"),
  थैंक्स: q("sarhao", "sarhao", "sarhao"),
  सर: q("guruji", "guruji", "guruji"),
  मैडम: q("guruji", "guruji", "guruji"),
  टीचर: q("guruji", "guruji", "guruji"),

  // Seasons, Weather & Nature
  मौसम: q("din-kalom", "din-kalom", "din-kalom"),
  तेज: q("ludhur", "ludhur", "ludhur"),
  चमका: q("bhati-yena", "julum-yena", "julum-yena"),
  काले: q("hende", "hende", "hende"),
  बादल: q("rimil", "rimil", "rimil"),
  "छप छप": q("chap chap", "chap chap", "chap chap"),

  // Helpers, Community & Village
  किसान: q("chasa", "chasa", "chasa"),
  खेत: q("khet", "khet", "khet"),
  पाठशाला: q("itun-asra", "iskul", "iskul"),
  पढ़ाते: q("parhaoa", "parhaowa", "parhaowa"),
  मददगार: q("gorho-ij", "gora-ij", "gora-ij"),
  समुदाय: q("horko", "hoko", "hoko"),

  // Cleanliness & Health
  रोज: q("din-hilok", "din-hilang", "din-hilang"),
  धोना: q("abuk", "abug", "abug"),
  धो: q("abuk me", "abug me", "abug me"),
  धोओ: q("abuk me", "abug me", "abug me"),
  स्वच्छ: q("sapha", "sapha", "sapha"),
  स्वस्थ: q("bes", "bugin", "bugin"),

  // Colors, Shapes & Art
  पत्ता: q("sakam", "sakam", "sakam"),
  पीला: q("sasang", "sasang", "sasang"),
  नीला: q("lile", "lili", "lili"),
  गोल: q("gol", "gol", "gol"),
  चौकोर: q("char-kuna", "char-kuna", "char-kuna"),
  खिड़की: q("khirki", "khirki", "khirki"),
  चित्र: q("chitar", "chitar", "chitar"),
  बनाओ: q("benao me", "bai me", "bai me"),
  भरो: q("perec me", "peree me", "peree me"),

  // Forests, Rivers & Earth
  जंगल: q("bir", "bir", "bir"),
  ठंडा: q("rear", "rear", "rear"),
  लगाओ: q("rohe me", "rohe me", "rohe me"),
  बचाओ: q("banchao me", "banchao me", "banchao me"),
  धरती: q("dharti", "dharti", "dharti"),
  प्रकृति: q("sirjon", "sirjon", "sirjon"),

  // Folk Tales & Rhymes
  मीठा: q("sibil", "sibil", "sibil"),
  पहेली: q("kudum", "kudum", "kudum"),
  पहेलियाँ: q("kudumko", "kudumko", "kudumko"),
  बुझो: q("bujhau me", "bujhau me", "bujhau me"),
  मातृभाषा: q("ayobhasha", "ayobhasha", "ayobhasha"),
  रानी: q("rani", "rani", "rani"),
  राजा: q("raja", "raja", "raja"),
};

Object.assign(LEXICON, EXTRA_LEXICON);

/** Full-sentence phrase memory — takes priority over word-by-word. */
export const PHRASES: Record<string, Entry> = {
  "तुम्हारा नाम क्या है": e(
    ["am nutum chet kana", "ᱟᱢ ᱧᱩᱛᱩᱢ ᱪᱮᱫᱽ ᱠᱟᱱᱟ"],
    ["amah nutum chi tana", "𑣁𑣢𑣁 𑣙𑣂𑣔𑣂𑣢 𑣋𑣂 𑣔𑣁𑣙"],
    ["amaa nutum chi tana", "आमा नुतुम ची ताना"],
  ),
  "तुमने आज क्या क्या सीखा": e(
    ["tehen am chet kom chedket", "ᱛᱮᱦᱮᱸ ᱟᱢ ᱪᱮᱫ ᱠᱚᱢ ᱪᱮᱫᱠᱮᱫ"],
    ["tisin am chi kom itukeda", "𑣔𑣂𑣜𑣂𑣙 𑣁𑣢 𑣋𑣂 𑣄𑣉𑣢 𑣂𑣔𑣂𑣄𑣕𑣞𑣁"],
    ["tisin am chi kom itukeda", "तिसिन आम ची कोम इतुकेदा"],
  ),
  "तुमने आज क्या सीखा": e(
    ["tehen am chet em chedket", "ᱛᱮᱦᱮᱸ ᱟᱢ ᱪᱮᱫ ᱮᱢ ᱪᱮᱫᱠᱮᱫ"],
    ["tisin am chi em itukeda", "𑣔𑣂𑣜𑣂𑣙 𑣁𑣢 𑣋𑣂 𑣕𑣢 𑣂𑣔𑣂𑣄𑣕𑣞𑣁"],
    ["tisin am chi em itukeda", "तिसिन आम ची एम इतुकेदा"],
  ),
  "आज तुमने क्या सीखा": e(
    ["tehen am chet em chedket", "ᱛᱮᱦᱮᱸ ᱟᱢ ᱪᱮᱫ ᱮᱢ ᱪᱮᱫᱠᱮᱫ"],
    ["tisin am chi em itukeda", "𑣔𑣂𑣜𑣂𑣙 𑣁𑣢 𑣋𑣂 𑣕𑣢 𑣂𑣔𑣂𑣄𑣕𑣞𑣁"],
    ["tisin am chi em itukeda", "तिसिन आम ची एम इतुकेदा"],
  ),
  "आज तुमने क्या क्या सीखा": e(
    ["tehen am chet kom chedket", "ᱛᱮᱦᱮᱸ ᱟᱢ ᱪᱮᱫ ᱠᱚᱢ ᱪᱮᱫᱠᱮᱫ"],
    ["tisin am chi kom itukeda", "𑣔𑣂𑣜𑣂𑣙 𑣁𑣢 𑣋𑣂 𑣄𑣉𑣢 𑣂𑣔𑣂𑣄𑣕𑣞𑣁"],
    ["tisin am chi kom itukeda", "तिसिन आम ची कोम इतुकेदा"],
  ),
  "आपने आज क्या सीखा": e(
    ["tehen ape chet pe chedket", "ᱛᱮᱦᱮᱸ ᱟᱯᱮ ᱪᱮᱫ ᱯᱮ ᱪᱮᱫᱠᱮᱫ"],
    ["tisin am chi em itukeda", "𑣔𑣂𑣜𑣂𑣙 𑣁𑣢 𑣋𑣂 𑣕𑣢 𑣂𑣔𑣂𑣄𑣕𑣞𑣁"],
    ["tisin ape chi pe itukeda", "तिसिन आपे ची पे इतुकेदा"],
  ),
  "म्याऊं म्याऊं": e(
    ["meao meao", "ᱢᱮᱭᱟᱣ ᱢᱮᱭᱟᱣ"],
    ["miaw miaw", "𑣢𑣂𑣁𑣓 𑣢𑣂𑣁𑣓"],
    ["miaw miaw", "मियाव मियाव"],
  ),
  "म्याऊँ म्याऊँ": e(
    ["meao meao", "ᱢᱮᱭᱟᱣ ᱢᱮᱭᱟᱣ"],
    ["miaw miaw", "𑣢𑣂𑣁𑣓 𑣢𑣂𑣁𑣓"],
    ["miaw miaw", "मियाव मियाव"],
  ),
  "हेलो हाउ आर यू": e(
    ["johar am chet leka menama", "ᱡᱚᱦᱟᱨ ᱟᱢ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱢᱟ"],
    ["johar am chilekan menama", "𑢠𑣉𑣁𑣜 𑣁𑣢 𑣋𑣂𑣗𑣕𑣄𑣁𑣙 𑣢𑣕𑣙𑣁𑣢𑣁"],
    ["johar am chilekan menama", "जोहार आम चिलेकान मेनामा"],
  ),
  "हलो हाउ आर यू": e(
    ["johar am chet leka menama", "ᱡᱚᱦᱟᱨ ᱟᱢ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱢᱟ"],
    ["johar am chilekan menama", "𑢠𑣉𑣁𑣜 𑣁𑣢 𑣋𑣂𑣗𑣕𑣄𑣁𑣙 𑣢𑣕𑣙𑣁𑣢𑣁"],
    ["johar am chilekan menama", "जोहार आम चिलेकान मेनामा"],
  ),
  "हेल्लो हाउ आर यू": e(
    ["johar am chet leka menama", "ᱡᱚᱦᱟᱨ ᱟᱢ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱢᱟ"],
    ["johar am chilekan menama", "𑢠𑣉𑣁𑣜 𑣁𑣢 𑣋𑣂𑣗𑣕𑣄𑣁𑣙 𑣢𑣕𑣙𑣁𑣢𑣁"],
    ["johar am chilekan menama", "जोहार आम चिलेकान मेनामा"],
  ),
  "हाउ आर यू": e(
    ["chet leka menama", "ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱢᱟ"],
    ["chilekan menama", "𑣋𑣂𑣗𑣕𑣄𑣁𑣙 𑣢𑣕𑣙𑣁𑣢𑣁"],
    ["chilekan menama", "चिलेकान मेनामा"],
  ),
  "तुम कैसे हो": e(
    ["am chet leka menama", "ᱟᱢ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱢᱟ"],
    ["am chilekan menama", "𑣁𑣢 𑣋𑣂𑣗𑣕𑣄𑣁𑣙 𑣢𑣕𑣙𑣁𑣢𑣁"],
    ["am chilekan menama", "आम चिलेकान मेनामा"],
  ),
  "आप कैसे हैं": e(
    ["am chet leka menama", "ᱟᱢ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱢᱟ"],
    ["am chilekan menama", "𑣁𑣢 𑣋𑣂𑣗𑣕𑣄𑣁𑣙 𑣢𑣕𑣙𑣁𑣢𑣁"],
    ["am chilekan menama", "आम चिलेकान मेनामा"],
  ),
  "मैं ठीक हूँ": e(
    ["ing bes ge menana", "ᱤᱧ ᱵᱮᱥ ᱜᱮ ᱢᱮᱱᱟᱧᱟ"],
    ["ain bugin menana", "𑣁𑣅𑣙 𑣢𑣂𑣍𑣂𑣙 𑣢𑣕𑣙𑣁𑣙𑣁"],
    ["ain bugin menana", "ऐन बुगिन मेनाना"],
  ),
  "मैं ठीक हूं": e(
    ["ing bes ge menana", "ᱤᱧ ᱵᱮᱥ ᱜᱮ ᱢᱮᱱᱟᱧᱟ"],
    ["ain bugin menana", "𑣁𑣅𑣙 𑣢𑣂𑣍𑣂𑣙 𑣢𑣕𑣙𑣁𑣙𑣁"],
    ["ain bugin menana", "ऐन बुगिन मेनाना"],
  ),
  "सब ठीक है": e(
    ["jotoh bes ge", "ᱡᱚᱛᱚ ᱵᱮᱥ ᱜᱮ"],
    ["saben bugin ge", "𑣜𑣁𑣢𑣕𑣙 𑣢𑣂𑣍𑣂𑣙 𑣍𑣕"],
    ["saben bugin ge", "सबेन बुगिन गे"],
  ),
  "सब बच्चे बैठ जाओ": e(
    ["jotoh gidrako durup pe", "ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹᱠᱚ ᱫᱩᱨᱩᱯ ᱯᱮ"],
    ["sabenko hoponko dub pe", "𑣜𑣁𑣢𑣕𑣙 𑣙𑣉𑣟𑣉𑣃 𑣞𑣂𑣢 𑣟𑣕"],
    ["sabenko honko dub pe", "सबेन होनको दुब पे"],
  ),
  "आज हम गिनती सीखेंगे": e(
    ["tehen abo lekha bo tolaa", "ᱛᱮᱦᱮᱸ ᱟᱵᱩ ᱞᱮᱠᱷᱟ ᱵᱚ ᱛᱚᱞᱟᱣᱟ"],
    ["tisin abu lekha bu itua", "𑣔𑣂𑣜𑣂𑣙 𑣁𑣢𑣂 𑣗𑣕𑣄𑣁"],
    ["tisin abu lekha bu itua", "तिसिन आबू लेखा बू इतुआ"],
  ),
  "ध्यान से सुनो": e(
    ["bes lekate anjom me", "ᱵᱮᱥ ᱞᱮᱠᱟᱛᱮ ᱟᱸᱡᱚᱢ ᱢᱮ"],
    ["bugin lekate ayum me", "𑣢𑣂𑣍𑣂 𑣁𑣜𑣂𑣂𑣢 𑣢𑣕"],
    ["bugin lekate ayum me", "बुगिन लेकाते आयुम मे"],
  ),
  "बहुत अच्छा": e(
    ["ale bes", "ᱟᱹᱰᱤ ᱵᱮᱥ"], ["pura bugin", "𑣟𑣂𑣜𑣁 𑣢𑣂𑣍𑣂"], ["pura bugin", "पुरा बुगिन"],
  ),
  "प्यार से बात करें": e(
    ["dular te ror bon", "ᱫᱩᱞᱟᱲ ᱛᱮ ᱨᱚᱲ ᱵᱚᱱ"],
    ["dulad te kaji bu", "𑣞𑣂𑣗𑣁𑣞 𑣔𑣕 𑣄𑣁𑣄𑣂"],
    ["dulad te kaji bu", "दुलाद ते काजी बू"],
  ),
  "प्यार से बात करो": e(
    ["dular te ror me", "ᱫᱩᱞᱟᱲ ᱛᱮ ᱨᱚᱲ ᱢᱮ"],
    ["dulad te kaji me", "𑣞𑣂𑣗𑣁𑣞 𑣔𑣕 𑣄𑣁𑣄𑣂"],
    ["dulad te kaji me", "दुलाद ते काजी मे"],
  ),
  "चित्र देखो": e(
    ["chitar nel me", "ᱪᱤᱛᱟᱨ ᱧᱮᱞ ᱢᱮ"],
    ["chitar nel me", "𑣋𑣂𑣔𑣁𑣜 𑣙𑣕𑣗 𑣢𑣕"],
    ["chitar nel me", "चितार नेल मे"],
  ),
};

/** English headword -> Hindi headword, so English speech/typing also translates. */
export const EN_TO_HI: Record<string, string> = {
  hello: "नमस्ते", hi: "नमस्ते", johar: "नमस्ते", greetings: "नमस्कार",
  children: "बच्चों", kids: "बच्चों", child: "बच्चा", student: "बच्चा", students: "बच्चों",
  "sit down": "बैठो", sit: "बैठो", "stand up": "उठो", stand: "उठो",
  listen: "सुनो", look: "देखो", see: "देखो", watch: "देखो",
  speak: "बोलो", say: "बोलो", talk: "बोलो", read: "पढ़ो", write: "लिखो",
  good: "अच्छा", nice: "अच्छा", "well done": "शाबाश", bravo: "शाबाश",
  yes: "हाँ", no: "नहीं", "thank you": "धन्यवाद", thanks: "धन्यवाद",
  mother: "माँ", mom: "माँ", father: "पिता", dad: "पिता",
  teacher: "गुरुजी", friend: "दोस्त", boy: "लड़का", girl: "लड़की",
  school: "स्कूल", book: "किताब", pen: "कलम", pencil: "कलम",
  water: "पानी", home: "घर", house: "घर", food: "खाना", village: "गाँव",
  sun: "सूरज", moon: "चाँद", tree: "पेड़", flower: "फूल",
  river: "नदी", mountain: "पहाड़", hill: "पहाड़", fire: "आग", rain: "बारिश",
  cow: "गाय", dog: "कुत्ता", goat: "बकरी", bird: "चिड़िया", fish: "मछली",
  eye: "आँख", eyes: "आँख", hand: "हाथ", head: "सिर", leg: "पैर", foot: "पैर",
  one: "एक", two: "दो", three: "तीन", four: "चार", five: "पाँच",
  six: "छह", seven: "सात", eight: "आठ", nine: "नौ", ten: "दस",
  "1": "एक", "2": "दो", "3": "तीन", "4": "चार", "5": "पाँच",
  "6": "छह", "7": "सात", "8": "आठ", "9": "नौ", "10": "दस",
  red: "लाल", black: "काला", white: "सफेद", green: "हरा",
  come: "आओ", go: "जाओ", play: "खेलो", count: "गिनो", tell: "बताओ",
  repeat: "दोहराओ", what: "क्या", who: "कौन", "how many": "कितने",
  love: "प्यार", with: "से", together: "साथ",
  work: "काम", do: "करो", we: "हम", you: "तुम", i: "मैं", he: "वह", she: "वह",
  this: "यह", where: "कहाँ", when: "कब", why: "क्यों", how: "कैसे",
  all: "सब", some: "कुछ", very: "बहुत", little: "थोड़ा", big: "बड़ा",
  small: "छोटा", new: "नया", bad: "बुरा", right: "सही", wrong: "गलत",
  happy: "खुश", heart: "दिल", mind: "मन", brother: "भाई", sister: "बहन",
  time: "समय", day: "दिन", night: "रात", morning: "सुबह", evening: "शाम",
  tomorrow: "कल", now: "अभी", stop: "रुको", help: "मदद", question: "सवाल",
  answer: "जवाब", learn: "सीखो", understand: "समझो", remember: "याद",
  again: "फिर", slowly: "धीरे", quickly: "जल्दी", song: "गीत", sing: "गीत",
  dance: "नाच", story: "कहानी", game: "खेल", hungry: "भूख", thirsty: "प्यास",
  milk: "दूध", rice: "चावल", bread: "रोटी", fruit: "फल", vegetable: "सब्जी",
  egg: "अंडा", stomach: "पेट", ear: "कान", mouth: "मुँह", tooth: "दाँत",
  hair: "बाल", sleep: "सो", take: "लो", give: "दे", open: "खोलो", close: "बंद",
  clean: "साफ", ask: "पूछो",
  today: "आज", name: "नाम", your: "तुम्हारा", my: "मेरा", is: "है", and: "और",
  cat: "बिल्ली", meow: "म्याऊं", am: "हूं", are: "हो",
};

/** English full-sentence aliases -> Hindi phrase key. */
export const EN_PHRASE_TO_HI: Record<string, string> = {
  "what is your name": "तुम्हारा नाम क्या है",
  "whats your name": "तुम्हारा नाम क्या है",
  "what's your name": "तुम्हारा नाम क्या है",
  "all children sit down": "सब बच्चे बैठ जाओ",
  "everyone sit down": "सब बच्चे बैठ जाओ",
  "children sit down": "सब बच्चे बैठ जाओ",
  "today we will learn counting": "आज हम गिनती सीखेंगे",
  "today we learn counting": "आज हम गिनती सीखेंगे",
  "listen carefully": "ध्यान से सुनो",
  "very good": "बहुत अच्छा",
  "look at the picture": "चित्र देखो",
  "speak with love": "प्यार से बात करो",
  "talk with love": "प्यार से बात करो",
  "how are you": "हाउ आर यू",
  "hello how are you": "हेलो हाउ आर यू",
  "hey how are you": "हेलो हाउ आर यू",
  "what did you learn today": "तुमने आज क्या सीखा",
  "what did you learn": "तुमने आज क्या सीखा",
};

export const SAMPLE_LESSONS = [
  {
    id: "fln-l1",
    title: "पाठ 1 — जोहार और परिचय",
    titleEn: "Lesson 1 — Johar & Introductions",
    outcome: "NIPUN Bharat • मौखिक भाषा विकास (ओ.एल.-1.1)",
    outcomeEn: "NIPUN Bharat • Oral language development (OL-1.1)",
    lines: ["नमस्ते बच्चों", "तुम्हारा नाम क्या है", "मेरा नाम है", "बहुत अच्छा"],
  },
  {
    id: "fln-l2",
    title: "पाठ 2 — गिनती 1 से 10",
    titleEn: "Lesson 2 — Counting 1 to 10",
    outcome: "NIPUN Bharat • संख्या ज्ञान एवं बुनियादी गणित (एन.-1.2)",
    outcomeEn: "NIPUN Bharat • Numeracy & Counting (N-1.2)",
    lines: ["आज हम गिनती सीखेंगे", "एक दो तीन चार पाँच", "छह सात आठ नौ दस", "गिनो और बताओ"],
  },
  {
    id: "fln-l3",
    title: "पाठ 3 — हमारे आस-पास की प्रकृति",
    titleEn: "Lesson 3 — The World Around Us",
    outcome: "NIPUN Bharat • शब्द भंडार एवं पर्यावरण बोध (ओ.एल.-1.4)",
    outcomeEn: "NIPUN Bharat • Environmental vocabulary (OL-1.4)",
    lines: ["सूरज चाँद नदी पहाड़", "पेड़ और फूल", "चित्र देखो", "बोलो और लिखो"],
  },
  {
    id: "fln-l4",
    title: "पाठ 4 — कक्षा के निर्देश",
    titleEn: "Lesson 4 — Classroom Instructions",
    outcome: "NIPUN Bharat • सुनना और समझना (ओ.एल.-1.2)",
    outcomeEn: "NIPUN Bharat • Listening comprehension (OL-1.2)",
    lines: ["सब बच्चे बैठ जाओ", "ध्यान से सुनो", "किताब खोलो और पढ़ो", "शाबाश बच्चों"],
  },
  {
    id: "fln-l5",
    title: "पाठ 5 — हमारा परिवार और घर",
    titleEn: "Lesson 5 — Family & Home",
    outcome: "NIPUN Bharat • पारिवारिक संबंध और सामाजिक संवाद (ओ.एल.-1.3)",
    outcomeEn: "NIPUN Bharat • Family relationships and social dialogue (OL-1.3)",
    lines: ["माँ और पिता", "भाई और बहन", "मेरा प्यारा घर", "प्यार से बात करो"],
  },
  {
    id: "fln-l6",
    title: "पाठ 6 — भोजन और अच्छी आदतें",
    titleEn: "Lesson 6 — Food & Healthy Habits",
    outcome: "NIPUN Bharat • स्वास्थ्य, पोषण और स्वच्छता (एच.-1.1)",
    outcomeEn: "NIPUN Bharat • Health, nutrition & hygiene (H-1.1)",
    lines: ["खाना खाओ और पानी पियो", "चावल और रोटी", "दूध और फल", "हाथ साफ करो"],
  },
  {
    id: "fln-l7",
    title: "पाठ 7 — पशु-पक्षी और उनकी आवाजें",
    titleEn: "Lesson 7 — Animals & Bird Sounds",
    outcome: "NIPUN Bharat • जीव-जंतु और ध्वनि अनुकरण (ई.वी.एस.-1.1)",
    outcomeEn: "NIPUN Bharat • Animal sounds & nature awareness (EVS-1.1)",
    lines: ["गाय और बकरी", "कुत्ता और बिल्ली", "म्याऊं म्याऊं", "चिड़िया और मछली"],
  },
  {
    id: "fln-l8",
    title: "पाठ 8 — खेल, गीत और क्रियाएं",
    titleEn: "Lesson 8 — Actions, Play & Rhymes",
    outcome: "NIPUN Bharat • शारीरिक गतिशीलता और क्रिया शब्द (ओ.एल.-1.6)",
    outcomeEn: "NIPUN Bharat • Physical play & action verbs (OL-1.6)",
    lines: ["आओ खेलें", "गीत गाओ और नाचो", "हंसो और खुश रहो", "सब मिलकर काम करो"],
  },
  {
    id: "fln-l9",
    title: "पाठ 9 — सुबह, शाम और दिनचर्या",
    titleEn: "Lesson 9 — Time, Morning & Routine",
    outcome: "NIPUN Bharat • समय, ऋतु और दैनिक कार्य (ई.वी.एस.-1.2)",
    outcomeEn: "NIPUN Bharat • Daily routine and day-night concepts (EVS-1.2)",
    lines: ["सूरज निकला सुबह हुई", "दिन और रात", "समय पर स्कूल चलो", "अभी पढ़ो"],
  },
  {
    id: "fln-l10",
    title: "पाठ 10 — बातचीत और प्रश्न-उत्तर",
    titleEn: "Lesson 10 — Questions & Conversation",
    outcome: "NIPUN Bharat • संवाद, प्रश्नोत्तरी और आत्मविश्वास (ओ.एल.-1.7)",
    outcomeEn: "NIPUN Bharat • Inquisitive dialogue & confidence (OL-1.7)",
    lines: ["तुम कैसे हो", "मैं ठीक हूँ", "तुमने आज क्या सीखा", "शाबाश बहुत अच्छा"],
  },
  {
    id: "fln-l11",
    title: "पाठ 11 — ऋतुएँ, मौसम और बारिश",
    titleEn: "Lesson 11 — Seasons, Weather & Rain",
    outcome: "NIPUN Bharat • पर्यावरण एवं ऋतु ज्ञान (ई.वी.एस.-1.3)",
    outcomeEn: "NIPUN Bharat • Weather, seasons & nature cycles (EVS-1.3)",
    lines: ["सूरज बहुत तेज चमका", "काले बादल आए", "बारिश का मौसम आया", "पानी में छप छप"],
  },
  {
    id: "fln-l12",
    title: "पाठ 12 — हमारे मददगार और समुदाय",
    titleEn: "Lesson 12 — Community Helpers & Village",
    outcome: "NIPUN Bharat • सामाजिक एवं सामुदायिक समझ (ओ.एल.-1.8)",
    outcomeEn: "NIPUN Bharat • Social helpers & village life (OL-1.8)",
    lines: ["किसान खेत में काम करता है", "गुरुजी पाठशाला में पढ़ाते हैं", "सब मिलकर काम करो", "हमारा सुंदर गाँव"],
  },
  {
    id: "fln-l13",
    title: "पाठ 13 — शरीर की स्वच्छता और सफाई",
    titleEn: "Lesson 13 — Personal Hygiene & Cleanliness",
    outcome: "NIPUN Bharat • व्यक्तिगत स्वच्छता और स्वास्थ्य (एच.-1.2)",
    outcomeEn: "NIPUN Bharat • Personal cleanliness & wellbeing (H-1.2)",
    lines: ["रोज सुबह हाथ धोना", "दाँत साफ करो", "साफ पानी पियो", "स्वच्छ रहो स्वस्थ रहो"],
  },
  {
    id: "fln-l14",
    title: "पाठ 14 — रंग, आकृतियाँ और चित्रकला",
    titleEn: "Lesson 14 — Colors, Shapes & Drawing",
    outcome: "NIPUN Bharat • रचनात्मक कला एवं दृश्य पहचान (सी.ए.-1.1)",
    outcomeEn: "NIPUN Bharat • Creative art & visual recognition (CA-1.1)",
    lines: ["लाल फूल और हरा पत्ता", "गोल सूरज चौकोर खिड़की", "सुंदर चित्र बनाओ", "रंग भरो और खुश हो"],
  },
  {
    id: "fln-l15",
    title: "पाठ 15 — जंगल, नदियाँ और हमारी धरती",
    titleEn: "Lesson 15 — Forests, Rivers & Native Earth",
    outcome: "NIPUN Bharat • प्रकृति संरक्षण और स्थानीय विरासत (ई.वी.एस.-1.4)",
    outcomeEn: "NIPUN Bharat • Ecology, rivers & tribal heritage (EVS-1.4)",
    lines: ["हरा-भरा जंगल और ऊँचे पहाड़", "नदी का ठंडा पानी", "पेड़ लगाओ धरती बचाओ", "प्रकृति हमारी माँ है"],
  },
  {
    id: "fln-l16",
    title: "पाठ 16 — लोकगीत, पहेलियाँ और बाल कहानी",
    titleEn: "Lesson 16 — Folk Rhymes, Riddles & Stories",
    outcome: "NIPUN Bharat • मौखिक अभिव्यक्ति और लोक साहित्य (ओ.एल.-1.9)",
    outcomeEn: "NIPUN Bharat • Folk storytelling & cultural memory (OL-1.9)",
    lines: ["एक जंगल में एक चिड़िया", "मीठा गीत सुनाओ", "पहेली बुझो और बताओ", "जोहार हमारी मातृभाषा"],
  },
];

export const FLASHCARD_SETS = [
  { id: "nature", label: "प्रकृति", labelEn: "Nature", words: ["सूरज", "चाँद", "पेड़", "फूल", "नदी", "पहाड़", "बारिश", "आग"] },
  { id: "animals", label: "जानवर", labelEn: "Animals", words: ["गाय", "कुत्ता", "बकरी", "चिड़िया", "मछली", "बिल्ली"] },
  { id: "numbers", label: "गिनती", labelEn: "Numbers", words: ["एक", "दो", "तीन", "चार", "पाँच", "छह", "सात", "आठ", "नौ", "दस"] },
  { id: "body", label: "शरीर", labelEn: "Body", words: ["आँख", "हाथ", "सिर", "पैर", "कान", "मुँह", "दाँत", "पेट"] },
  { id: "school", label: "पाठशाला", labelEn: "School", words: ["स्कूल", "किताब", "कलम", "पानी", "घर", "खाना", "गुरुजी", "दोस्त"] },
  { id: "colours", label: "रंग", labelEn: "Colours", words: ["लाल", "काला", "सफेद", "हरा"] },
  { id: "family", label: "परिवार", labelEn: "Family", words: ["माँ", "पिता", "भाई", "बहन", "बच्चा", "दोस्त"] },
  { id: "food", label: "भोजन", labelEn: "Food", words: ["खाना", "पानी", "चावल", "रोटी", "दूध", "फल", "सब्जी"] },
  { id: "actions", label: "क्रियाएं", labelEn: "Actions", words: ["बैठो", "उठो", "सुनो", "देखो", "बोलो", "पढ़ो", "लिखो", "खेलो"] },
  { id: "time", label: "समय व दिन", labelEn: "Time & Day", words: ["दिन", "रात", "सुबह", "शाम", "सूरज", "चाँद"] },
];

export const EMOJI_FOR: Record<string, string> = {
  सूरज: "☀️", चाँद: "🌙", पेड़: "🌳", फूल: "🌸", नदी: "🏞️", पहाड़: "⛰️", आग: "🔥", बारिश: "🌧️",
  गाय: "🐄", कुत्ता: "🐕", बकरी: "🐐", चिड़िया: "🐦", मछली: "🐟", बिल्ली: "🐱",
  एक: "1️⃣", दो: "2️⃣", तीन: "3️⃣", चार: "4️⃣", पाँच: "5️⃣", छह: "6️⃣",
  सात: "7️⃣", आठ: "8️⃣", नौ: "9️⃣", दस: "🔟",
  आँख: "👁️", हाथ: "✋", सिर: "🧑", पैर: "🦶", कान: "👂", मुँह: "👄", दाँत: "🦷", पेट: "🫄",
  स्कूल: "🏫", किताब: "📕", कलम: "🖊️", पानी: "💧", घर: "🏠", खाना: "🍚", गुरुजी: "👨‍🏫", दोस्त: "🤝",
  लाल: "🟥", काला: "⬛", सफेद: "⬜", हरा: "🟩",
  माँ: "👩", पिता: "👨", भाई: "👦", बहन: "👧", बच्चा: "👶",
  चावल: "🍚", रोटी: "🫓", दूध: "🥛", फल: "🍎", सब्जी: "🥦",
  बैठो: "🪑", उठो: "🧍", सुनो: "👂", देखो: "👀", बोलो: "🗣️", पढ़ो: "📖", लिखो: "✍️", खेलो: "⚽",
  दिन: "☀️", रात: "🌙", सुबह: "🌅", शाम: "🌇",
};
